sudo: false
language: go
go:
  - 1.9.x
matrix:
  fast_finish: true
install:
  - # go get golang.org/x/tools/cmd/cover
  - # go get github.com/mattn/goveralls
  - # Do not install go-github yet, since we want it to happen inside the script step.
script:
  - go get -t -v ./...
  - go test -v -race ./...

