sudo: false
language: go
go:
  - 1.9.x
matrix:
  allow_failures:
    - go: master
  fast_finish: true
script:
  - go get "github.com/sirupsen/logrus"
  - go get "github.com/gin-gonic/gin"
  - go get "github.com/google/go-github/github"
  - go get "golang.org/x/oauth2"
  - go get "github.com/franela/goblin"      
  - go test ...

